In [18]:
import numpy as np
A = np.array([1,2,3,4,5,6,7,8])

A.shape

(8,)

In [19]:
A.mean()

4.5

In [20]:
B = np.array([[1,2,3,4],[5,6,7,8]])
print(B)


[[1 2 3 4]
 [5 6 7 8]]


In [21]:
B.shape

(2, 4)

In [22]:
B.mean()

4.5

In [23]:
B.mean(axis = 0)

array([3., 4., 5., 6.])

In [25]:
C = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])

In [26]:
C.shape

(2, 2, 4)

In [27]:
C.mean(axis = 0)

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])